Setup:
  input_path: '/vols/cms/dmw25/TauTheDifference/Production/.output/ShuffleMerge/qqH/tt'
  model_outputs: 'XGB_Models/qqH_optimised/tt'
  model_dir_name: 'model_tt'

param: {
        'objective': 'multi:softmax',
        'n_estimators': 216,
        'lambda': 0.0005313627060666906,
        'subsample': 0.9639545163565166,
        'colsample_bytree': 0.898068334732543,
        'learning_rate': 0.6382996935033061,
        'max_depth': 3,
        'min_child_weight': 6
      }

Features:
  train: ['pt_1', 'pt_2',  # individual kinematics
          'met_pt','met_dphi_1', 'met_dphi_2', # met information
          'dR', 'dphi', 'pt_tt', 'm_vis', 'pt_vis', 'FastMTT_mass', # pair quantities
          'mt_1', 'mt_2', 'mt_lep', 'mt_tot', # transverse masses
          'jpt_1', 'jpt_2', 'jeta_1', 'jeta_2', # individual jets
          'mjj', 'jdeta', 'dijetpt', # dijet quantities
          'n_jets'] # global jet information
  weight: 'class_weight'
  truth: 'class_label'
