Setup:
  input_path: '/vols/cms/dmw25/TauTheDifference/Production/.output/ShuffleMerge/qqH/tt'
  model_outputs: 'XGB_Models/qqH_separate/tt'
  model_dir_name: 'model_tt'

param: {
        'objective': 'multi:softmax',
        'n_jobs': 4,
        'n_estimators': 507,
        'lambda': 0.0005939607885864436,
        'subsample': 0.8935925847880031,
        'colsample_bytree': 0.22747187595248855,
        'learning_rate': 0.030563084716245977,
        'max_depth': 6,
        'min_child_weight': 10
      }

Features:
  train: ['pt_1', 'pt_2',  # individual kinematics
          'met_pt','met_dphi_1', 'met_dphi_2', # met information
          'dR', 'dphi', 'pt_tt', 'm_vis', 'pt_vis', 'FastMTT_mass', # pair quantities
          'mt_1', 'mt_2', 'mt_lep', 'mt_tot', # transverse masses
          'jpt_1', 'jpt_2', 'jeta_1', 'jeta_2', # individual jets
          'mjj', 'jdeta', 'dijetpt', # dijet quantities
          'n_jets'] # global jet information
  weight: 'class_weight'
  truth: 'class_label'
